framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            'assets/': ''
            '%kernel.project_dir%/vendor/symfony/ux-turbo/assets/dist': '@symfony/ux-turbo'
        missing_import_mode: strict
        importmap_script_attributes:
            data-turbo-track: 'reload'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
